## Data Preprocessing

### Import Libraries

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
df = pd.read_csv('Datasets/Reliance.csv')
df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS
1,Date,NaN,NaN,NaN,NaN,NaN
2,2020-01-01,675.3241577148438,683.1528519736394,673.4900624593615,679.0819357370663,14004468
3,2020-01-02,686.8212280273438,689.3487905881979,676.397899264457,676.397899264457,17710316
4,2020-01-03,687.6488037109375,689.6618949086101,681.3187290426969,685.7922517653002,20984698

In [33]:
# removing the first two rows and resetting the index
df = df.iloc[2:].reset_index(drop=True)
df.head()

,Price,Close,High,Low,Open,Volume
0,2020-01-01,675.3241577148438,683.1528519736394,673.4900624593615,679.0819357370663,14004468
1,2020-01-02,686.8212280273438,689.3487905881979,676.397899264457,676.397899264457,17710316
2,2020-01-03,687.6488037109375,689.6618949086101,681.3187290426969,685.7922517653002,20984698
3,2020-01-06,671.70068359375,683.5107670428088,670.13493269889,679.9767186772816,24519177
4,2020-01-07,682.0346069335938,686.4633961016671,677.0689495898322,679.5293813804267,16683622

In [34]:
# Renaming the 'Price' column to 'Date'
df.rename(columns={"Price": "Date"}, inplace=True)
df.head()

,Date,Close,High,Low,Open,Volume
0,2020-01-01,675.3241577148438,683.1528519736394,673.4900624593615,679.0819357370663,14004468
1,2020-01-02,686.8212280273438,689.3487905881979,676.397899264457,676.397899264457,17710316
2,2020-01-03,687.6488037109375,689.6618949086101,681.3187290426969,685.7922517653002,20984698
3,2020-01-06,671.70068359375,683.5107670428088,670.13493269889,679.9767186772816,24519177
4,2020-01-07,682.0346069335938,686.4633961016671,677.0689495898322,679.5293813804267,16683622

In [35]:
# Converting all column names to lowercase
df.columns = df.columns.str.lower()
df.head()

,date,close,high,low,open,volume
0,2020-01-01,675.3241577148438,683.1528519736394,673.4900624593615,679.0819357370663,14004468
1,2020-01-02,686.8212280273438,689.3487905881979,676.397899264457,676.397899264457,17710316
2,2020-01-03,687.6488037109375,689.6618949086101,681.3187290426969,685.7922517653002,20984698
3,2020-01-06,671.70068359375,683.5107670428088,670.13493269889,679.9767186772816,24519177
4,2020-01-07,682.0346069335938,686.4633961016671,677.0689495898322,679.5293813804267,16683622

In [36]:
# Dataframe information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1238 entries, 0 to 1237
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1238 non-null   object
 1   close   1238 non-null   object
 2   high    1238 non-null   object
 3   low     1238 non-null   object
 4   open    1238 non-null   object
 5   volume  1238 non-null   object
dtypes: object(6)
memory usage: 58.2+ KB

In [37]:
import os

print(os.listdir("Datasets"))

['data.py', 'HDFC_Bank.csv', 'Infosys.csv', 'Maruti.csv', 'Reliance.csv', 'Sun_Pharma.csv']

### Cleaned Datasets into new folder

In [38]:
companys =["Reliance","Infosys", "HDFC_Bank", "Sun_Pharma", "Maruti"] 

for company in companys:
    df = pd.read_csv(f"Datasets/{company}.csv")
    df = df.iloc[2:].reset_index(drop=True)
    df.rename(columns={"Price": "Date"}, inplace=True)
    df.columns = df.columns.str.lower()
    df.to_csv(f"cleaned_datasets/{company}.csv", index=False)
    print(df.shape)

(1238, 6)
(1238, 6)
(1238, 6)
(1238, 6)
(1238, 6)

In [39]:
reliance_df = pd.read_csv("cleaned_datasets/Reliance.csv")
reliance_df.head()

         date       close        high         low        open    volume
0  2020-01-01  675.324158  683.152852  673.490062  679.081936  14004468
1  2020-01-02  686.821228  689.348791  676.397899  676.397899  17710316
2  2020-01-03  687.648804  689.661895  681.318729  685.792252  20984698
3  2020-01-06  671.700684  683.510767  670.134933  679.976719  24519177
4  2020-01-07  682.034607  686.463396  677.068950  679.529381  16683622

In [40]:
reliance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1238 entries, 0 to 1237
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1238 non-null   object
 1   close   1238 non-null   float64
 2   high    1238 non-null   float64
 3   low     1238 non-null   float64
 4   open    1238 non-null   float64
 5   volume  1238 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 58.2+ KB

In [41]:
reliance_df.describe()

             close         high          low         open        volume
count  1238.000000  1238.000000  1238.000000  1238.000000  1.238000e+03
mean   1100.161477  1112.124803  1089.250153  1101.029341  1.951391e+07
std     231.543415   231.765308   231.155858   231.430430  1.612248e+07
min     395.482483   424.985412   391.724705   409.864862  1.705656e+06
25%     955.397797   966.569660   946.793368   955.971028  1.009199e+07
50%    1120.744812  1133.024521  1111.124100  1122.159968  1.425293e+07
75%    1224.963013  1238.659281  1213.518228  1224.827693  2.203644e+07
max    1589.138062  1596.980044  1573.851280  1592.662006  1.426834e+08

In [42]:
reliance_df.isnull().sum()

date      0
close     0
high      0
low       0
open      0
volume    0
dtype: int64

In [43]:
reliance_df['date'] = pd.to_datetime(reliance_df['date'])
reliance_df = reliance_df.sort_values('date').reset_index(drop=True)
reliance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1238 entries, 0 to 1237
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1238 non-null   datetime64[ns]
 1   close   1238 non-null   float64
 2   high    1238 non-null   float64
 3   low     1238 non-null   float64
 4   open    1238 non-null   float64
 5   volume  1238 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 58.2 KB

In [44]:
df.set_index('date', inplace=True)
df.head()

,close,high,low,open,volume
date,,,,,
2020-01-01,6945.3349609375,7038.661976772966,6917.170253808878,7007.362807310255,634725
2020-01-02,6962.576171875,6998.814512015528,6945.620482065356,6960.438911743073,616838
2020-01-03,6890.763671875,6964.617878097322,6863.929185369783,6961.720888974127,571967
2020-01-06,6689.5283203125,6848.730526280027,6674.425109973177,6839.231593511262,748516
2020-01-07,6719.16552734375,6806.555713385005,6674.330376805239,6744.242618401264,590500